config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tasks#doing"
  resources :users, only: [:edit, :update]
  resources :tags, only: [:index,:new, :show,:create,:destroy] do
    resources :tasks do
      member do
        put "finish"
      end
    end
  end
  get  "tasks/done"  => "tasks#done"
  get  "tasks/doing"  => "tasks#doing"
  get  "tasks/calendar"  => "tasks#calendar"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/done.rb
class Done < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tasks,dependent: :destroy
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :tag
  belongs_to :user
  validates :name, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :tags,dependent: :destroy
  has_many :tasks,dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  protect_from_forgery :except => [:destroy]
  # before_action :correct_user 
  def index
    @tags = Tag.where(user_id: current_user.id)
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to tag_tasks_path(@tag), notice: 'タグを作成しました'
    else
      render :new
    end
  end

  def destroy
    tag = Tag.find(params[:id])
    if tag.destroy
      redirect_to root_path
    else
      render :destroy
    end

  end

  private
  def tag_params
    params.require(:tag).permit(:name).merge(user_id: current_user.id)
  end
  def correct_user
    @tag = current_user.tags.find_by(id: params[:id])
      unless @tag
        redirect_to root_url
      end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  protect_from_forgery :except => [:destroy]
  before_action :set_tag,except:[:done,:doing,:calendar]
  before_action :set_task,only:[:edit]
  before_action :correct_user ,only:[:edit,:destroy]


  def index    
    @tasks = @tag.tasks.includes(:user).order("deadline ASC")
    @tags = Tag.where(user_id: current_user.id)

  end
  
  def new
    # @task=Task.find(params[:tag_id])
    if current_user.id == @tag.user_id
      @task = Task.new
    else
      redirect_to root_path
    end
  end

  def create
    @task = @tag.tasks.new(task_params)
    if @task.save
      redirect_to tag_tasks_path(@tag)
    else
      render :new
    end
    
  end

  def finish
    @task = Task.find(params[:id])
    if @task.completed.present?
      @task.update_attribute(:completed, nil)
      redirect_to tasks_done_path
    else
      @task.update_attribute(:completed, true)
      redirect_to tag_tasks_path(@tag)
    end
  end

  def done
    @done = Task.where(user_id: current_user.id,completed:1).order("deadline ASC")
    @tags = Tag.where(user_id: current_user.id)
  end

  def doing
    @done = Task.where(user_id: current_user.id,completed:nil).order("deadline ASC")
    @tags = Tag.where(user_id: current_user.id)
  end

  def calendar
    @tags = Tag.where(user_id: current_user.id)
    @tasks = Task.where(user_id: current_user.id)
  end

  def edit
  end

  def update
    task=Task.find(params[:id])
    task.update(task_params)
    redirect_to tag_tasks_path(@tag)

  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    if @task.completed.present?
      redirect_to tasks_done_path
    else
      redirect_to tag_tasks_path(@tag)
    end
  end

  private

  def task_params
    params.require(:task).permit(:name,:deadline,:detail).merge(user_id: current_user.id)
  end

  def set_tag
    @tag = Tag.find(params[:tag_id])
  end
  def set_task
    @task = Task.find(params[:id])
  end
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
      unless @task
        redirect_to root_url
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name=>"viewport" ,:content=>"width=device-width,initial-scale=1.0"}
    %title Todo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %script{src:"./jquery-3.4.1.min.js"}
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"}
    %link{rel:"stylesheet", href:"https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css"}
    %link{rel:"stylesheet", href:"https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css"}
    = javascript_include_tag 'application'
  %body
    = yield

app/views/tags/_bar.html.haml
.Main
  .Main-header
    .Main-header__Name
      =link_to root_path,class:"AppName" do
        %div TO DO
    .Main-header__Box
      .UserName
        = link_to edit_user_path(current_user) do
          = current_user.name
      -# .Edit
      -#   = link_to "#" do
      -#     =icon('fas','cog')
  .Main-contents
    -# = link_to "#",class:"finish" do
    -#   %div 完了
    %ul.Tags
      = link_to   tasks_done_path,class:"tag-done" do
        %li.done 完了
      = link_to   tasks_doing_path,class:"tag-doing" do
        %li.doing 未完了
        
      - @tags.each do |tags|
        %li.tag
          = link_to  tag_tasks_path(tags),method: :get,class:"tag-new" do
            = tags.name
          = link_to tag_path(tags.id) ,method: :delete,class:"delete" do
            =icon('fas','times')
    = link_to new_tag_path ,class:"tag-icon" do
      =icon('fas','plus')

app/views/tags/index.html.haml
= render "bar"

app/views/tags/new.html.haml
.tags-form
  .tag-form
    .form-title タグ追加
    = form_with model: @tag, local: true do |f|
      = f.text_field :name, class: "tag-form__input", placeholder: "タグ名を入力してください"
      = f.submit "追加する", class: "tag-form__button"

app/views/tags/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'form') %>");
$("#user-modal").modal("show");

app/views/tasks/_main.html.haml
.Contents
  .Contents__Tasks
    - @tasks.each do |task|
      - if current_user.id == task.user_id
        - if task.completed.present?
          .not-main
        - else 
          .list
            .main
              .task
                .task-title 
                  = task.name
                .task-date
                - if task.deadline.present? 
                  = task.deadline.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[task.deadline.wday]}) %H:%M")
              .icons
                .icon
                  = link_to  finish_tag_task_path(task.tag.id,task.id)  ,method: :put do
                    = icon('fas','check')
                .icon
                  = link_to  edit_tag_task_path(task.tag.id,task.id),method: :get do
                    = icon('fas','pen')
                .icon
                  = link_to  tag_task_path(task.tag.id,task.id) , method: :delete do
                    = icon('fas','trash-alt')
          -if task.detail.present?
            .content
              %ul
                %li 
                  =safe_join(task.detail.split("\n"),tag(:br))
              .button 
                = icon('fas','chevron-down')
          - else
            .not-content
  .Contents__New-task
    = link_to new_tag_task_path,class:"Newtask" do
      = icon('far','edit')

app/views/tasks/_task.html.haml
-# .list
-#   .task
-#     .task-title 
-#       = current_user.task.name
-#     .task-date
-#     - if task.deadline.present? 
-#       = current_user.task.deadline.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[task.deadline.wday]}) %H:%M")
-#   .icons
-#     -# .icon
-#     -#   = link_to "#" do
-#     -#     = icon('fas','check')
-#     .icon
-#       = link_to  edit_tag_task_path(task.tag.id,task.id),method: :get do
-#         = icon('fas','pen')
-#     .icon
-#       = link_to  tag_task_path(task.tag.id,task.id) , method: :delete do
-#         = icon('fas','trash-alt')

app/views/tasks/calendar.html.haml
.wrapper
  = render "tags/bar" 
  .calendar-main
    #calendar

     

app/views/tasks/doing.html.haml
.wrapper
  = render "tags/bar" 
  .Contents
    .Contents__Tasks
      - @done.each do |task|
        - if current_user.id == task.user_id
          .list
            .main
              .task
                .task-title 
                  = task.name
                .task-date
                - if task.deadline.present? 
                  = task.deadline.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[task.deadline.wday]}) %H:%M")
              .icons
                .icon
                  = link_to  finish_tag_task_path(task.tag.id,task.id)  ,method: :put do
                    = icon('fas','check')
                .icon
                  = link_to  edit_tag_task_path(task.tag.id,task.id),method: :get do
                    = icon('fas','pen')
                .icon
                  = link_to  tag_task_path(task.tag.id,task.id) , method: :delete do
                    = icon('fas','trash-alt')
          -if task.detail.present?
            .content
              %ul
                %li 
                  =task.detail
              .button 
                = icon('fas','chevron-down')
          - else
            .not-content

app/views/tasks/done.html.haml
.wrapper
  = render "tags/bar" 
  .Contents
    .Contents__Tasks
      - @done.each do |task|
        - if current_user.id == task.user_id
          .list
            .main
              .task
                .task-title 
                  = task.name
                .task-date
                - if task.deadline.present? 
                  = task.deadline.strftime("%m/%d(#{%w(日 月 火 水 木 金 土)[task.deadline.wday]}) %H:%M")
              .icons
                .icon
                  = link_to  finish_tag_task_path(task.tag.id,task.id)  ,method: :put do
                    = icon('fas','check')
                .icon
                  = link_to  edit_tag_task_path(task.tag.id,task.id),method: :get do
                    = icon('fas','pen')
                .icon
                  = link_to  tag_task_path(task.tag.id,task.id) , method: :delete do
                    = icon('fas','trash-alt')
          -if task.detail.present?
            .content
              %ul
                %li 
                  =task.detail
              .button 
                = icon('fas','chevron-down')
          - else
            .not-content

app/views/tasks/edit.html.haml
.tasks-form
  .task-form
    .form-title タスク編集
    = form_with model:[@tag,@task], local: true do |f|
      .task-label
        = f.label :name,"タスク名"
      .task-input
        = f.text_field :name, placeholder: "タスクを入力してください"
      .detail-label
        = f.label :detail,"詳細"
      .detail-date
        = f.text_area :detail
      .date-label
        = f.label :deadline,"期限"
      .date
        = f.datetime_field :deadline
      .task-button
        -# = f.time_field :deadline
        = f.submit "Save"

app/views/tasks/index.html.haml
.wrapper
  = render "tags/bar" 
  = render "main"

app/views/tasks/new.html.haml
.tasks-form
  .task-form
    .form-title タスク追加
    = form_with model:[@tag,@task], local: true do |f|
      .task-label
        = f.label :name,"タスク名"
      .task-input
        = f.text_field :name, placeholder: "タスクを入力してください"
      .detail-label
        = f.label :detail,"詳細"
      .detail-date
        = f.text_area :detail
      .date-label
        = f.label :deadline,"期限"
      .date
        = f.datetime_field :deadline
      .task-button
        -# = f.time_field :deadline
        = f.submit "追加"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 アカウントの編集 
    = link_to "トップページに戻る", :back, class: 'button3'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name,"名前"
        .FormField__input--normal
          = f.text_field :name, placeholder:"名前",autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email,"メールアドレス"
        .FormField__input--normal
          = f.email_field :email,placeholder:"メールアドレス"
      .FormField
        .FormField__label--normal
          = f.label :password,"パスワード"
        .FormField__input--normal
          = f.password_field :password,placeholder:"パスワード(英数字8文字以上)", autocomplete: "off"
      .actions
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'button4'
        = f.submit "更新", class: 'button2 UserButton update'